//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common_M.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common_M.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing SSIS package.
        /// </summary>
        internal static string Missing_SSIS_package {
            get {
                return ResourceManager.GetString("Missing_SSIS_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of input file path parameter missing.
        /// </summary>
        internal static string Name_of_input_file_path_parameter_missing {
            get {
                return ResourceManager.GetString("Name_of_input_file_path_parameter_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of output path parameter missing.
        /// </summary>
        internal static string Name_of_output_path_parameter_missing {
            get {
                return ResourceManager.GetString("Name_of_output_path_parameter_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSIS package not found.
        /// </summary>
        internal static string SSIS_package_not_found {
            get {
                return ResourceManager.GetString("SSIS_package_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp directory does not exist or cannot be accessed. Job: {0}.
        /// </summary>
        internal static string Temp_directory_does_not_exist_or_cannot_be_accessed {
            get {
                return ResourceManager.GetString("Temp_directory_does_not_exist_or_cannot_be_accessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp directory is missing in job configuration. Job: {0}.
        /// </summary>
        internal static string Temp_directory_is_missing_in_job_configuration {
            get {
                return ResourceManager.GetString("Temp_directory_is_missing_in_job_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification of SSIS file location failed! {0} Job: {1}.
        /// </summary>
        internal static string Verification_of_SSIS_package_location_failed_0 {
            get {
                return ResourceManager.GetString("Verification_of_SSIS_package_location_failed_0", resourceCulture);
            }
        }
    }
}
